#!/bin/bash

source ~/.config/dalarma/config.sh

SUCCESS_EXIT_CODE=42
WIN_TITLE="dalarma_win"
DALARMAS_PATH="/tmp/dalarma/"

delta_from_now() {
    given_time=$(date -d "$1" +%s)
    current_time=$(date +%s)
    delta_seconds=$((given_time - current_time))
    echo "${delta_seconds}s"
}

parse_time() {
    if [[ "$1" == *":"* ]]; then
        delta_from_now "$1"
    else
        echo "$1"
    fi
}

TERMINAL_SCRIPT_KEYWORD=IS_TERMINAL_SCRIPT
if [ "$1" = "$TERMINAL_SCRIPT_KEYWORD" ]; then
    while true; do
        time_remaining=$(( $LOCK_START-$(date +%s)+$LOCK_TIME ))
        if (( $time_remaining <= 0 )); then
            break
        fi

        clear
        if [ -n "$TITLE" ]; then
            echo "Alarma: $TITLE"
        fi
        echo "Lock time remaining: $time_remaining"
        echo "To close immediately, solve next task:"
        echo "$TASK_TEXT"

        read -p "Answer: " inp
        if [ "$inp" = "$TASK_SOLVE" ]; then
            break
        fi
    done

    exit $SUCCESS_EXIT_CODE
fi



if [ -z "$1" ]; then
    echo "Usage: $0 number[s|m|h|d] [text]"
    echo "More info about [s|m|h|d] see in 'man sleep'"
    notify-send -u critical "can't start dalarma"

    exit 1
fi

raw_user_sleep_time=$1
export TITLE="${@:2}"

# TODO: there should be flag detection and setting custom lock time
# default 15 if not set in config
export LOCK_TIME=${LOCK_TIME:-15}

notify-send -t 1000 "dalarma started for $raw_user_sleep_time" "$TITLE"

sleep_time=$(parse_time "$raw_user_sleep_time")

# store meta info to be used by external programs
mkdir -p "$DALARMAS_PATH"
cur_dalarma_tmp="$DALARMAS_PATH/$$"
echo "
    started_at=\"$(date '+%H:%M')\"
    sleep_time=\"$sleep_time\"
    raw_user_sleep_time=\"$raw_user_sleep_time\"
    title=\"$TITLE\"
" > "$cur_dalarma_tmp"

sleep "$sleep_time"

# preparation for lock program
export TASK_SOLVE=$(date +%N | md5sum | head -c 10)
export TASK_TEXT="Type   '$TASK_SOLVE'"
export LOCK_START=$(date +%s)

(sleep $LOCK_TIME && notify-send -u critical "dalarma break done") &
PID_NOTIFY_BREAK_DONE=$!

# re-read config one time again, just for the case when you edited config
# after creating dalarma timer
source ~/.config/dalarma/config.sh

# pre lock
notify-send -u critical "dalarma" "$TITLE"
cmd_pre_lock

# force focus and make fullscreen our "window"
# initial little sleep is hack to make window fullscreen as soon as possible
# (idea is in that this background loop will start already after terminal
# window started)
(sleep 0.1 && while true; do
    wmctrl -r "$WIN_TITLE" -b add,fullscreen
    wmctrl -a "$WIN_TITLE"
    sleep 1
done) &
PID_LOCKWIN_LOOP=$!

# lock
while true; do
    EXIT_STRING=$(st -t "$WIN_TITLE" -f "Monospace:pixelsize=50:antialias=true:autohint=true" \
        -e sh -c "dalarma $TERMINAL_SCRIPT_KEYWORD" 2>&1)

    if [ "$EXIT_STRING" = "child exited with status $SUCCESS_EXIT_CODE" ]; then
        break
    fi
done

# post lock
kill $PID_LOCKWIN_LOOP
kill $PID_NOTIFY_BREAK_DONE 2> /dev/null
# remove meta info file for current alarma
rm "$cur_dalarma_tmp"
dunstctl close-all
cmd_post_lock
